<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Los estándares de calidad – AESDE</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../TallerA/taller-github.html" rel="next">
<link href="../tema2/sesion3.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-5a1953863e1f72ef3b996ef827f01ca7.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5278fcfdc973cccf35a68fa14a1d1781.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-42d6a4eb5a8c5103ab4d7fae467d72b5.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-5278fcfdc973cccf35a68fa14a1d1781.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">AESDE</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-prácticas" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Prácticas</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-prácticas">    
        <li>
    <a class="dropdown-item" href="https://elrobin.github.io/aesde-26">
 <span class="dropdown-text">26-27 Biblioteca Colegio Máximo</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://elrobin.github.io"> 
<span class="menu-text">Más sobre mí</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/elrobin/aesde"> <i class="bi bi-github" role="img" aria-label="Source Code">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../tema3/sesion1.html">T3 La familia ISO 9000</a></li><li class="breadcrumb-item"><a href="../tema3/sesion1.html">Los estándares de calidad</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación de la asignatura</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">T1 El sistema de información empresarial</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema1/sesion1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dato, información y documento</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema1/sesion2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tipos y funciones de los sistemas de información</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">T2 Calidad: concepto y evaluación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema2/sesion1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">El concepto de calidad y sus dimensiones</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema2/sesion2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gestión de la calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema2/sesion3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Diseño del instrumento de calidad percibida</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">T3 La familia ISO 9000</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema3/sesion1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Los estándares de calidad</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../TallerA/taller-github.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Taller Github+Quarto</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#distinción-entre-sistema-y-subsistema" id="toc-distinción-entre-sistema-y-subsistema" class="nav-link active" data-scroll-target="#distinción-entre-sistema-y-subsistema">Distinción entre sistema y subsistema</a></li>
  <li><a href="#los-estándares-de-calidad" id="toc-los-estándares-de-calidad" class="nav-link" data-scroll-target="#los-estándares-de-calidad">Los estándares de calidad</a>
  <ul class="collapse">
  <li><a href="#organizaciones-responsables-de-emitir-normativas-y-estándares" id="toc-organizaciones-responsables-de-emitir-normativas-y-estándares" class="nav-link" data-scroll-target="#organizaciones-responsables-de-emitir-normativas-y-estándares">Organizaciones responsables de emitir normativas y estándares</a></li>
  <li><a href="#la-certificación-de-la-calidad" id="toc-la-certificación-de-la-calidad" class="nav-link" data-scroll-target="#la-certificación-de-la-calidad">La certificación de la calidad</a></li>
  </ul></li>
  <li><a href="#la-familia-iso-9000" id="toc-la-familia-iso-9000" class="nav-link" data-scroll-target="#la-familia-iso-9000">La familia ISO 9000</a>
  <ul class="collapse">
  <li><a href="#evolución-de-las-normas-iso-9000" id="toc-evolución-de-las-normas-iso-9000" class="nav-link" data-scroll-target="#evolución-de-las-normas-iso-9000">Evolución de las normas ISO 9000</a></li>
  </ul></li>
  <li><a href="#los-7-principios-de-la-gestión-de-la-calidad" id="toc-los-7-principios-de-la-gestión-de-la-calidad" class="nav-link" data-scroll-target="#los-7-principios-de-la-gestión-de-la-calidad">Los 7 principios de la gestión de la calidad</a>
  <ul class="collapse">
  <li><a href="#conceptos-clave" id="toc-conceptos-clave" class="nav-link" data-scroll-target="#conceptos-clave">Conceptos clave</a></li>
  </ul></li>
  <li><a href="#tareas" id="toc-tareas" class="nav-link" data-scroll-target="#tareas">Tareas</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/elrobin/aesde/edit/main/tema3/sesion1.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/elrobin/aesde/issues/new" class="toc-action"><i class="bi empty"></i>Informar sobre problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../tema3/sesion1.html">T3 La familia ISO 9000</a></li><li class="breadcrumb-item"><a href="../tema3/sesion1.html">Los estándares de calidad</a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Los estándares de calidad</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Código</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="distinción-entre-sistema-y-subsistema" class="level2">
<h2 class="anchored" data-anchor-id="distinción-entre-sistema-y-subsistema">Distinción entre sistema y subsistema</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../images/t3-sistema-subsistemas.svg" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Relación entre diferentes subsistemas dentro de un mismo sistema de gestión de información</figcaption>
</figure>
</div>
<div class="ejercicio">
<p>Clasificad cada elemento según pertenezca a la <strong>Biblioteca Universitaria de Granada (BUG)</strong>, a la <strong>Biblioteca del Colegio Máximo</strong> o a <strong>ambas</strong>:</p>
<ul>
<li>El Reglamento de la Biblioteca Universitaria</li>
<li>Las normas de acceso y uso complementarias de la Biblioteca del Colegio Máximo</li>
<li>El Sello de Excelencia Europea EFQM 600+</li>
<li>El horario de apertura de la sala de lectura</li>
<li>La carta de servicios</li>
<li>La encuesta de satisfacción de usuarios</li>
<li>Las quejas y sugerencias presentadas en el mostrador del Colegio Máximo</li>
<li>Las estadísticas anuales de préstamo</li>
</ul>
<p>Guardad vuestra clasificación: la retomaremos al final de la sesión.</p>
</div>
</section>
<section id="los-estándares-de-calidad" class="level2">
<h2 class="anchored" data-anchor-id="los-estándares-de-calidad">Los estándares de calidad</h2>
<p>La integración de sistemas TQM en las empresas es considerada como un indicio de la calidad del mismo. Sin embargo, para transmitir confianza a clientes y otras organizaciones externas, así como para homogeneizar procesos, las organizaciones acuden a entidades externas de validación de sus servicios.</p>
<p>Esto es lo que se conoce como la <strong>normalización de procesos mediante la creación de estándares o normas</strong>. Esto es, <u>fijar un conjunto de requisitos comunes, acordados internacionalmente, con los que cualquier organización puede compararse</u>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>¿Qué es una norma o estándar?
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Una norma es un documento elaborado por consenso y aprobado por un organismo reconocido, que establece reglas o características para un uso común y repetido</strong>.</p>
</div>
</div>
<p>Las normas tienen dos características esenciales:</p>
<ol type="1">
<li>Son <mark><strong>de carácter voluntario</strong></mark>. Ninguna ley obliga a cumplir una norma o estándar. Su fuerza viene del mercado y de quien la exige (clientes, administraciones, convocatorias).</li>
<li>Son <mark><strong>fruto del consenso</strong></mark>. La redacción viene dada por parte de expertos internacionales que forman comités técnicos para su diseño y aprobación.</li>
</ol>
<section id="organizaciones-responsables-de-emitir-normativas-y-estándares" class="level3">
<h3 class="anchored" data-anchor-id="organizaciones-responsables-de-emitir-normativas-y-estándares">Organizaciones responsables de emitir normativas y estándares</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Nivel</th>
<th>Organismo</th>
<th>Qué hace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Internacional</td>
<td><strong>ISO</strong></td>
<td>Elabora las normas en comités técnicos. La familia 9000 es del <strong>ISO/TC 176</strong></td>
</tr>
<tr class="even">
<td>Europeo</td>
<td><strong>CEN</strong></td>
<td>Las adopta como normas europeas (EN)</td>
</tr>
<tr class="odd">
<td>Español</td>
<td><strong>UNE</strong> (Asociación Española de Normalización)</td>
<td>Las publica en España como <strong>UNE-EN ISO</strong></td>
</tr>
</tbody>
</table>
<p>La familia de normas que se centran en la gestión de la calidad es la familia <em>UNE-EN ISO 9000</em>.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Distinción entre UNE y AENOR
</div>
</div>
<div class="callout-body-container callout-body">
<p>En algunos trabajos se hablará indistintamente de <strong>AENOR</strong> y <strong>UNE</strong>. Sin embargo, desde 2017 operan como organizaciones distintas:</p>
<ul>
<li>UNE publica normas y estándares.</li>
<li>AENOR certifica que las organizaciones cumplen con dichas normas.</li>
</ul>
</div>
</div>
</section>
<section id="la-certificación-de-la-calidad" class="level3">
<h3 class="anchored" data-anchor-id="la-certificación-de-la-calidad">La certificación de la calidad</h3>
<p>Normalmente, una organización que cumple con el estándar en cualquiera de sus procesos querrá certificar dicho cumplimiento. Para ello, deberá buscar una entidad independiente que lo certifique.</p>
<p>El recorrido tiene cuatro pasos:</p>
<ol type="1">
<li><strong>ISO publica una norma.</strong> Por ejemplo, la ISO 9001, que establece qué requisitos debe cumplir un sistema de gestión de la calidad.</li>
<li><strong>Una organización la adopta.</strong> Decide organizar su gestión según esos requisitos. Para esto no necesita permiso de nadie ni ningún certificado: puede aplicar la norma sin certificarse nunca.</li>
<li><strong>La organización quiere demostrarlo.</strong> Decir “cumplimos la ISO 9001” no basta para generar confianza en usuarios, clientes o administraciones. Por eso pide a una <strong>entidad de certificación</strong> independiente (AENOR, Bureau Veritas, SGS…) que la audite. Si cumple los requisitos, la entidad le concede un <strong>certificado</strong>. Dura tres años, con auditorías de seguimiento cada año.</li>
<li><strong>Una entidad certificadora debe estar acreditada para constar como tal</strong>. Para ello, un organismo oficial que la evalúa y la <strong>acredita</strong> como competente para certificar. En España es <strong>ENAC</strong>. A su vez, ENAC forma parte de acuerdos internacionales (IAF), y por eso un certificado emitido en España es reconocido en otros países.</li>
</ol>
<p>Así, cada nivel da confianza al siguiente: ENAC respalda a AENOR y AENOR respalda a la organización. ISO queda fuera de esa cadena: <strong>escribe las normas, pero no certifica a nadie.</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {"theme": "base", "themeVariables": {"fontSize": "18px", "textColor": "#000", "edgeLabelBackground": "#ffffff"}}}%%
flowchart LR
  subgraph NOR["LA NORMA"]
    direction TB
    ISO["ISO&lt;br/&gt;internacional"]:::norma --&gt; CEN["CEN&lt;br/&gt;europeo"]:::norma --&gt; UNE["UNE&lt;br/&gt;España"]:::norma
  end

  ORG["ORGANIZACIÓN"]:::org

  subgraph CON["LA CONFIANZA"]
    direction TB
    IAF["IAF&lt;br/&gt;internacional"]:::confianza -- "4. reconoce" --&gt; ENAC["ENAC&lt;br/&gt;España"]:::confianza
    ENAC -- "4. acredita" --&gt; CB["AENOR u otra&lt;br/&gt;certificadora"]:::confianza
  end

  NOR -- "1. publica&lt;br/&gt;la norma" --&gt; ORG
  ORG -- "2. la adopta y&lt;br/&gt;3. pide auditoría" --&gt; CON
  CON -- "3. concede el&lt;br/&gt;certificado" --&gt; ORG

  classDef norma fill:#cfe2f3,stroke:#1f4e79,color:#000
  classDef confianza fill:#fff2cc,stroke:#bf9000,color:#000
  classDef org fill:#d9ead3,stroke:#38761d,stroke-width:3px,color:#000
  style NOR fill:#f2f7fc,stroke:#1f4e79,stroke-width:2px,color:#1f4e79
  style CON fill:#fffaeb,stroke:#bf9000,stroke-width:2px,color:#8a6800
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Alcance de un certificado
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un certificado tiene siempre un <strong>alcance</strong>: qué parte de la organización y qué actividades cubre. Una organización puede certificar algunos de sus servicios y no otros.</p>
</div>
</div>
</section>
</section>
<section id="la-familia-iso-9000" class="level2">
<h2 class="anchored" data-anchor-id="la-familia-iso-9000">La familia ISO 9000</h2>
<p>Cuando se habla de “la ISO 9000” no se habla de una sola norma, sino de un <strong>conjunto de normas sobre gestión de la calidad</strong> que elabora el mismo comité de ISO (el ISO/TC 176). Cada una cumple una función distinta, y conviene tenerlas claras desde el principio:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Norma</th>
<th>Qué es</th>
<th>Para qué sirve</th>
<th>¿Certificable?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="../lecturas/UNE-EN_ISO_9000=2026.pdf"><strong>ISO 9000</strong></a></td>
<td>Fundamentos y vocabulario</td>
<td><strong>Explica</strong> los conceptos y los principios de la gestión de la calidad. Es el diccionario de la familia</td>
<td>No</td>
</tr>
<tr class="even">
<td><a href="../lecturas/UNE-EN_ISO_9001=2026.pdf"><strong>ISO 9001</strong></a></td>
<td>Requisitos</td>
<td><strong>Exige</strong>: dice qué debe cumplir una organización para tener un sistema de gestión de la calidad</td>
<td><strong>Sí, es la única</strong></td>
</tr>
<tr class="odd">
<td><strong>ISO 9004</strong></td>
<td>Orientaciones</td>
<td><strong>Orienta</strong> a la organización que quiere ir más allá de los requisitos mínimos</td>
<td>No</td>
</tr>
<tr class="even">
<td><strong>ISO 19011</strong></td>
<td>Directrices de auditoría</td>
<td>Explica cómo auditar un sistema de gestión</td>
<td>No</td>
</tr>
</tbody>
</table>
<p>Por eso, cuando una organización dice que “tiene la ISO 9000”, lo correcto sería decir que está <strong>certificada con la ISO 9001</strong>: es la única de la familia que se puede certificar.</p>
<p>En esta sesión nos centramos en la ISO 9000; la 9001 y la 9004 son el contenido de la próxima.</p>
<section id="evolución-de-las-normas-iso-9000" class="level3">
<h3 class="anchored" data-anchor-id="evolución-de-las-normas-iso-9000">Evolución de las normas ISO 9000</h3>
<p>Las normas ISO se revisan periódicamente. La familia 9000 nació en 1987 y ha tenido seis ediciones. Algunas fueron simples retoques; otras cambiaron la forma de entender la gestión de la calidad. Estas son las importantes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Edición</th>
<th>Qué cambió</th>
<th>Qué significa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1987</strong></td>
<td>Nace la familia. Había <strong>tres normas certificables</strong>, y la organización elegía una según lo que hacía: la 9001 si diseñaba y producía, la 9002 si solo producía y la 9003 si solo inspeccionaba el producto final</td>
<td>La calidad se entendía como <strong>control</strong>: demostrar, con documentos, que el producto cumplía lo pactado</td>
</tr>
<tr class="even">
<td><strong>2000</strong></td>
<td>Las tres normas certificables se fusionan en <strong>una sola ISO 9001</strong>. La organización que no hace algo (por ejemplo, diseño) lo indica y queda exento de esos requisitos</td>
<td>La calidad pasa a entenderse como <strong>gestión</strong>: organizar el trabajo en procesos, pensando en el cliente y en la mejora continua</td>
</tr>
<tr class="odd">
<td><strong>2015</strong></td>
<td>Todas las normas ISO de gestión (calidad, medio ambiente, seguridad de la información…) adoptan <strong>la misma estructura de capítulos</strong>, para poder aplicarlas juntas. Se pide anticipar <strong>riesgos</strong>. Se reduce la obligación de redactar documentos</td>
<td>La calidad se integra en la gestión general de la organización, <strong>con menos papeleo</strong></td>
</tr>
<tr class="even">
<td><strong>2026</strong></td>
<td>Nuevas versiones de la ISO 9000 (mayo) y la ISO 9001 (septiembre). Las organizaciones certificadas tienen hasta 2029 para adaptarse</td>
<td>Más peso a la <strong>cultura</strong> de la organización y al <strong>comportamiento ético</strong> de la dirección</td>
</tr>
</tbody>
</table>
<p>Entre medias hubo revisiones menores: en 1994, en 2008 y una enmienda en 2024 que pide considerar el cambio climático.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>ISO 9002 o la 9003
</div>
</div>
<div class="callout-body-container callout-body">
<p>En bibliografía antigua aparecen las ISO 9002 y 9003. Son las normas de 1987 que desaparecieron en el año 2000, al fusionarse en la 9001. Existe una <strong>ISO/TS 9002:2016</strong>, pero no tiene nada que ver: es una guía para aplicar la ISO 9001 y no se puede certificar.</p>
</div>
</div>
</section>
</section>
<section id="los-7-principios-de-la-gestión-de-la-calidad" class="level2">
<h2 class="anchored" data-anchor-id="los-7-principios-de-la-gestión-de-la-calidad">Los 7 principios de la gestión de la calidad</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Principio</th>
<th>En una frase</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1. Enfoque al cliente</strong></td>
<td>Entender y satisfacer las necesidades de los usuarios, presentes y futuras</td>
</tr>
<tr class="even">
<td><strong>2. Liderazgo</strong></td>
<td>La dirección marca el rumbo y crea las condiciones para lograr los objetivos</td>
</tr>
<tr class="odd">
<td><strong>3. Compromiso de las personas</strong></td>
<td>Personas competentes, implicadas y con capacidad de decisión en todos los niveles</td>
</tr>
<tr class="even">
<td><strong>4. Enfoque a procesos</strong></td>
<td>Gestionar actividades interrelacionadas como procesos que forman un sistema</td>
</tr>
<tr class="odd">
<td><strong>5. Mejora</strong></td>
<td>Mejorar de forma continua, no solo corregir errores</td>
</tr>
<tr class="even">
<td><strong>6. Toma de decisiones basada en la evidencia</strong></td>
<td>Decidir a partir del análisis de datos e información</td>
</tr>
<tr class="odd">
<td><strong>7. Gestión de las relaciones</strong></td>
<td>Gestionar la relación con proveedores, socios y otras partes interesadas</td>
</tr>
</tbody>
</table>
<p>En 2015 los 8 principios anteriores se redujeron a 7: el “enfoque de sistema” se integró en el enfoque a procesos.</p>
<blockquote class="blockquote">
<p><strong>Pregunta:</strong> ¿Qué principio conecta directamente con el trabajo de un documentalista?*</p>
</blockquote>
<section id="conceptos-clave" class="level3">
<h3 class="anchored" data-anchor-id="conceptos-clave">Conceptos clave</h3>
<p>Definiciones simplificadas a partir de ISO 9000. Para la definición exacta, consultad la norma.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Concepto</th>
<th>Qué significa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Calidad</strong></td>
<td>Grado en que las características de un producto o servicio cumplen los requisitos</td>
</tr>
<tr class="even">
<td><strong>Requisito</strong></td>
<td>Necesidad o expectativa, ya sea declarada, implícita u obligatoria</td>
</tr>
<tr class="odd">
<td><strong>Parte interesada</strong></td>
<td>Persona u organización que puede afectar a una decisión, verse afectada por ella o percibirse afectada</td>
</tr>
<tr class="even">
<td><strong>Proceso</strong></td>
<td>Conjunto de actividades que transforman entradas en salidas</td>
</tr>
<tr class="odd">
<td><strong>Sistema de gestión de la calidad</strong></td>
<td>Parte del sistema de gestión de la organización que se ocupa de la calidad</td>
</tr>
<tr class="even">
<td><strong>Alcance</strong></td>
<td>Límites del sistema: qué parte de la organización y qué actividades cubre</td>
</tr>
<tr class="odd">
<td><strong>Información documentada</strong></td>
<td>Información que la organización debe controlar y mantener, y el medio que la contiene</td>
</tr>
<tr class="even">
<td><strong>Eficacia / eficiencia</strong></td>
<td>Lograr lo planificado / relación entre el resultado y los recursos empleados</td>
</tr>
<tr class="odd">
<td><strong>No conformidad</strong></td>
<td>Incumplimiento de un requisito</td>
</tr>
</tbody>
</table>
<p>Fijaos en la conexión con el Tema 1: un <strong>proceso</strong> con entradas y salidas es un sistema, y el <strong>alcance</strong> es su frontera con el entorno.</p>
</section>
</section>
<section id="tareas" class="level1">
<h1>Tareas</h1>
<div class="ejercicio">
<dl>
<dt><strong>La experiencia de la BUG</strong></dt>
<dd>
Moreno Pascual, L. (2016). <a href="https://dialnet.unirioja.es/servlet/articulo?codigo=6530614">El proceso de evaluación según el modelo EFQM: experiencia en la Biblioteca Universitaria de Granada</a>. Boletín de la asociación andaluza de bibliotecarios, 31(112), 84-100.
</dd>
</dl>
<p><strong>Objetivo.</strong> Pasar de los principios abstractos de la ISO 9000 a evidencias concretas, distinguiendo qué corresponde a la organización y qué al punto de servicio.</p>
<p><strong>Instrucciones.</strong></p>
<ol type="1">
<li><p>Localizad la documentación pública de calidad de la BUG (memorias EFQM, carta de servicios, política de calidad, resultados de encuestas) y la específica de la Biblioteca del Colegio Máximo (normas complementarias, información en la web, carteles, lo que observéis en persona).</p></li>
<li><p>Para cada uno de los <strong>7 principios</strong>, buscad <strong>una evidencia concreta</strong>. Si no la encontráis, indicadlo: la ausencia también es un resultado.</p></li>
<li><p>Recogedlo en una tabla en el repositorio del caso práctico:</p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Principio</th>
<th>Evidencia</th>
<th>Fuente</th>
<th>Nivel (BUG / Colegio Máximo / ambos)</th>
<th>¿Se aplica o solo se declara?</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<p>La columna <strong>Nivel</strong> es obligatoria. Usad la pregunta de control: <em>si cerrara el Colegio Máximo, ¿esto seguiría existiendo?</em></p></li>
<li><p>En vuestra página individual del wiki: ¿qué principio os ha costado más situar en un nivel y por qué?</p></li>
</ol>
<p><strong>Entrega.</strong> Commit al repositorio antes de que acabe la clase.</p>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/elrobin\.github\.io\/aesde\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../tema2/sesion3.html" class="pagination-link" aria-label="Diseño del instrumento de calidad percibida">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Diseño del instrumento de calidad percibida</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../TallerA/taller-github.html" class="pagination-link" aria-label="Taller Github+Quarto">
        <span class="nav-page-text">Taller Github+Quarto</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Los estándares de calidad"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">## Distinción entre sistema y subsistema</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="al">![Relación entre diferentes subsistemas dentro de un mismo sistema de gestión de información](/images/t3-sistema-subsistemas.svg)</span>{width="100%"}</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>::: ejercicio</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>Clasificad cada elemento según pertenezca a la **Biblioteca Universitaria de Granada (BUG)**, a la **Biblioteca del Colegio Máximo** o a **ambas**:</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>El Reglamento de la Biblioteca Universitaria</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Las normas de acceso y uso complementarias de la Biblioteca del Colegio Máximo</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>El Sello de Excelencia Europea EFQM 600+</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>El horario de apertura de la sala de lectura</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La carta de servicios</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La encuesta de satisfacción de usuarios</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Las quejas y sugerencias presentadas en el mostrador del Colegio Máximo</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Las estadísticas anuales de préstamo</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>Guardad vuestra clasificación: la retomaremos al final de la sesión.</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">## Los estándares de calidad</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>La integración de sistemas TQM en las empresas es considerada como un indicio de la calidad del mismo. Sin embargo, para transmitir confianza a clientes y otras organizaciones externas, así como para homogeneizar procesos, las organizaciones acuden a entidades externas de validación de sus servicios.</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>Esto es lo que se conoce como la **normalización de procesos mediante la creación de estándares o normas**. Esto es, <span class="co">[</span><span class="ot">fijar un conjunto de requisitos comunes, acordados internacionalmente, con los que cualquier organización puede compararse</span><span class="co">]</span>{.underline}.</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>::: callout-important</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## ¿Qué es una norma o estándar?</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>**Una norma es un documento elaborado por consenso y aprobado por un organismo reconocido, que establece reglas o características para un uso común y repetido**.</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>Las normas tienen dos características esenciales:</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Son <span class="co">[</span><span class="ot">**de carácter voluntario**</span><span class="co">]</span>{.mark}. Ninguna ley obliga a cumplir una norma o estándar. Su fuerza viene del mercado y de quien la exige (clientes, administraciones, convocatorias).</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Son <span class="co">[</span><span class="ot">**fruto del consenso**</span><span class="co">]</span>{.mark}. La redacción viene dada por parte de expertos internacionales que forman comités técnicos para su diseño y aprobación.</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="fu">### Organizaciones responsables de emitir normativas y estándares</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Nivel <span class="pp">|</span> Organismo <span class="pp">|</span> Qué hace <span class="pp">|</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="pp">|------------------------|------------------------|------------------------|</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Internacional <span class="pp">|</span> **ISO** | Elabora las normas en comités técnicos. La familia 9000 es del **ISO/TC 176** <span class="pp">|</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Europeo <span class="pp">|</span> **CEN** <span class="pp">|</span> Las adopta como normas europeas (EN) <span class="pp">|</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Español <span class="pp">|</span> **UNE** (Asociación Española de Normalización) | Las publica en España como **UNE-EN ISO** <span class="pp">|</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>La familia de normas que se centran en la gestión de la calidad es la familia *UNE-EN ISO 9000*.</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>::: callout-warning</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="fu">## Distinción entre UNE y AENOR</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>En algunos trabajos se hablará indistintamente de **AENOR** y **UNE**. Sin embargo, desde 2017 operan como organizaciones distintas:</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>UNE publica normas y estándares.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>AENOR certifica que las organizaciones cumplen con dichas normas.</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="fu">### La certificación de la calidad</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>Normalmente, una organización que cumple con el estándar en cualquiera de sus procesos querrá certificar dicho cumplimiento. Para ello, deberá buscar una entidad independiente que lo certifique.</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>El recorrido tiene cuatro pasos:</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**ISO publica una norma.** Por ejemplo, la ISO 9001, que establece qué requisitos debe cumplir un sistema de gestión de la calidad.</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Una organización la adopta.** Decide organizar su gestión según esos requisitos. Para esto no necesita permiso de nadie ni ningún certificado: puede aplicar la norma sin certificarse nunca.</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**La organización quiere demostrarlo.** Decir "cumplimos la ISO 9001" no basta para generar confianza en usuarios, clientes o administraciones. Por eso pide a una **entidad de certificación** independiente (AENOR, Bureau Veritas, SGS...) que la audite. Si cumple los requisitos, la entidad le concede un **certificado**. Dura tres años, con auditorías de seguimiento cada año.</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>**Una entidad certificadora debe estar acreditada para constar como tal**. Para ello, un organismo oficial que la evalúa y la **acredita** como competente para certificar. En España es **ENAC**. A su vez, ENAC forma parte de acuerdos internacionales (IAF), y por eso un certificado emitido en España es reconocido en otros países.</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>Así, cada nivel da confianza al siguiente: ENAC respalda a AENOR y AENOR respalda a la organización. ISO queda fuera de esa cadena: **escribe las normas, pero no certifica a nadie.**</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="in">```{mermaid}</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>%<span class="dt">%</span>{init: {<span class="ot">"</span><span class="st">theme</span><span class="ot">"</span>: <span class="ot">"</span><span class="st">base</span><span class="ot">"</span>, <span class="ot">"</span><span class="st">themeVariables</span><span class="ot">"</span>: {<span class="ot">"</span><span class="st">fontSize</span><span class="ot">"</span>: <span class="ot">"</span><span class="st">18px</span><span class="ot">"</span>, <span class="ot">"</span><span class="st">textColor</span><span class="ot">"</span>: <span class="ot">"</span><span class="st">#000</span><span class="ot">"</span>, <span class="ot">"</span><span class="st">edgeLabelBackground</span><span class="ot">"</span>: <span class="ot">"</span><span class="st">#ffffff</span><span class="ot">"</span>}}}%%</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>flowchart LR</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>  subgraph NOR[<span class="ot">"</span><span class="st">LA NORMA</span><span class="ot">"</span>]</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>    direction TB</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>    ISO[<span class="ot">"</span><span class="st">ISO&lt;br/&gt;internacional</span><span class="ot">"</span>]:::norma --&gt; CEN[<span class="ot">"</span><span class="st">CEN&lt;br/&gt;europeo</span><span class="ot">"</span>]:::norma --&gt; UNE[<span class="ot">"</span><span class="st">UNE&lt;br/&gt;España</span><span class="ot">"</span>]:::norma</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>  end</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>  ORG[<span class="ot">"</span><span class="st">ORGANIZACIÓN</span><span class="ot">"</span>]:::org</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>  subgraph CON[<span class="ot">"</span><span class="st">LA CONFIANZA</span><span class="ot">"</span>]</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>    direction TB</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>    IAF[<span class="ot">"</span><span class="st">IAF&lt;br/&gt;internacional</span><span class="ot">"</span>]:::confianza -- <span class="ot">"</span><span class="st">4. reconoce</span><span class="ot">"</span> --&gt; ENAC[<span class="ot">"</span><span class="st">ENAC&lt;br/&gt;España</span><span class="ot">"</span>]:::confianza</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>    ENAC -- <span class="ot">"</span><span class="st">4. acredita</span><span class="ot">"</span> --&gt; CB[<span class="ot">"</span><span class="st">AENOR u otra&lt;br/&gt;certificadora</span><span class="ot">"</span>]:::confianza</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>  end</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>  NOR -- <span class="ot">"</span><span class="st">1. publica&lt;br/&gt;la norma</span><span class="ot">"</span> --&gt; ORG</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>  ORG -- <span class="ot">"</span><span class="st">2. la adopta y&lt;br/&gt;3. pide auditoría</span><span class="ot">"</span> --&gt; CON</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>  CON -- <span class="ot">"</span><span class="st">3. concede el&lt;br/&gt;certificado</span><span class="ot">"</span> --&gt; ORG</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>  classDef norma fill:<span class="co">#cfe2f3,stroke:#1f4e79,color:#000</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>  classDef confianza fill:<span class="co">#fff2cc,stroke:#bf9000,color:#000</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>  classDef org fill:<span class="co">#d9ead3,stroke:#38761d,stroke-width:3px,color:#000</span></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>  style NOR fill:<span class="co">#f2f7fc,stroke:#1f4e79,stroke-width:2px,color:#1f4e79</span></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>  style CON fill:<span class="co">#fffaeb,stroke:#bf9000,stroke-width:2px,color:#8a6800</span></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="fu">## Alcance de un certificado</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>Un certificado tiene siempre un **alcance**: qué parte de la organización y qué actividades cubre. Una organización puede certificar algunos de sus servicios y no otros.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="fu">## La familia ISO 9000</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>Cuando se habla de "la ISO 9000" no se habla de una sola norma, sino de un **conjunto de normas sobre gestión de la calidad** que elabora el mismo comité de ISO (el ISO/TC 176). Cada una cumple una función distinta, y conviene tenerlas claras desde el principio:</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Norma <span class="pp">|</span> Qué es <span class="pp">|</span> Para qué sirve <span class="pp">|</span> ¿Certificable? <span class="pp">|</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="pp">|------------------|------------------|------------------|------------------|</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">**ISO 9000**</span><span class="co">](/lecturas/UNE-EN_ISO_9000=2026.pdf)</span> <span class="pp">|</span> Fundamentos y vocabulario <span class="pp">|</span> **Explica** los conceptos y los principios de la gestión de la calidad. Es el diccionario de la familia <span class="pp">|</span> No <span class="pp">|</span></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">**ISO 9001**</span><span class="co">](/lecturas/UNE-EN_ISO_9001=2026.pdf)</span> <span class="pp">|</span> Requisitos <span class="pp">|</span> **Exige**: dice qué debe cumplir una organización para tener un sistema de gestión de la calidad | **Sí, es la única** <span class="pp">|</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **ISO 9004** | Orientaciones | **Orienta** a la organización que quiere ir más allá de los requisitos mínimos <span class="pp">|</span> No <span class="pp">|</span></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **ISO 19011** <span class="pp">|</span> Directrices de auditoría <span class="pp">|</span> Explica cómo auditar un sistema de gestión <span class="pp">|</span> No <span class="pp">|</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>Por eso, cuando una organización dice que "tiene la ISO 9000", lo correcto sería decir que está **certificada con la ISO 9001**: es la única de la familia que se puede certificar.</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>En esta sesión nos centramos en la ISO 9000; la 9001 y la 9004 son el contenido de la próxima.</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a><span class="fu">### Evolución de las normas ISO 9000</span></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>Las normas ISO se revisan periódicamente. La familia 9000 nació en 1987 y ha tenido seis ediciones. Algunas fueron simples retoques; otras cambiaron la forma de entender la gestión de la calidad. Estas son las importantes:</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Edición <span class="pp">|</span> Qué cambió <span class="pp">|</span> Qué significa <span class="pp">|</span></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a><span class="pp">|------------------------|------------------------|------------------------|</span></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **1987** | Nace la familia. Había **tres normas certificables**, y la organización elegía una según lo que hacía: la 9001 si diseñaba y producía, la 9002 si solo producía y la 9003 si solo inspeccionaba el producto final | La calidad se entendía como **control**: demostrar, con documentos, que el producto cumplía lo pactado <span class="pp">|</span></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **2000** | Las tres normas certificables se fusionan en **una sola ISO 9001**. La organización que no hace algo (por ejemplo, diseño) lo indica y queda exento de esos requisitos | La calidad pasa a entenderse como **gestión**: organizar el trabajo en procesos, pensando en el cliente y en la mejora continua <span class="pp">|</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **2015** | Todas las normas ISO de gestión (calidad, medio ambiente, seguridad de la información...) adoptan **la misma estructura de capítulos**, para poder aplicarlas juntas. Se pide anticipar **riesgos**. Se reduce la obligación de redactar documentos | La calidad se integra en la gestión general de la organización, **con menos papeleo** <span class="pp">|</span></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **2026** | Nuevas versiones de la ISO 9000 (mayo) y la ISO 9001 (septiembre). Las organizaciones certificadas tienen hasta 2029 para adaptarse | Más peso a la **cultura** de la organización y al **comportamiento ético** de la dirección <span class="pp">|</span></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>Entre medias hubo revisiones menores: en 1994, en 2008 y una enmienda en 2024 que pide considerar el cambio climático.</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="fu">## ISO 9002 o la 9003</span></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>En bibliografía antigua aparecen las ISO 9002 y 9003. Son las normas de 1987 que desaparecieron en el año 2000, al fusionarse en la 9001. Existe una **ISO/TS 9002:2016**, pero no tiene nada que ver: es una guía para aplicar la ISO 9001 y no se puede certificar.</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a><span class="fu">## Los 7 principios de la gestión de la calidad</span></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Principio <span class="pp">|</span> En una frase <span class="pp">|</span></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a><span class="pp">|------------------------------------|------------------------------------|</span></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **1. Enfoque al cliente** <span class="pp">|</span> Entender y satisfacer las necesidades de los usuarios, presentes y futuras <span class="pp">|</span></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **2. Liderazgo** <span class="pp">|</span> La dirección marca el rumbo y crea las condiciones para lograr los objetivos <span class="pp">|</span></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **3. Compromiso de las personas** <span class="pp">|</span> Personas competentes, implicadas y con capacidad de decisión en todos los niveles <span class="pp">|</span></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **4. Enfoque a procesos** <span class="pp">|</span> Gestionar actividades interrelacionadas como procesos que forman un sistema <span class="pp">|</span></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **5. Mejora** <span class="pp">|</span> Mejorar de forma continua, no solo corregir errores <span class="pp">|</span></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **6. Toma de decisiones basada en la evidencia** <span class="pp">|</span> Decidir a partir del análisis de datos e información <span class="pp">|</span></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **7. Gestión de las relaciones** <span class="pp">|</span> Gestionar la relación con proveedores, socios y otras partes interesadas <span class="pp">|</span></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>En 2015 los 8 principios anteriores se redujeron a 7: el "enfoque de sistema" se integró en el enfoque a procesos.</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Pregunta:** ¿Qué principio conecta directamente con el trabajo de un documentalista?*</span></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conceptos clave</span></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>Definiciones simplificadas a partir de ISO 9000. Para la definición exacta, consultad la norma.</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Concepto <span class="pp">|</span> Qué significa <span class="pp">|</span></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="pp">|------------------------------------|------------------------------------|</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Calidad** <span class="pp">|</span> Grado en que las características de un producto o servicio cumplen los requisitos <span class="pp">|</span></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Requisito** <span class="pp">|</span> Necesidad o expectativa, ya sea declarada, implícita u obligatoria <span class="pp">|</span></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Parte interesada** <span class="pp">|</span> Persona u organización que puede afectar a una decisión, verse afectada por ella o percibirse afectada <span class="pp">|</span></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Proceso** <span class="pp">|</span> Conjunto de actividades que transforman entradas en salidas <span class="pp">|</span></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Sistema de gestión de la calidad** <span class="pp">|</span> Parte del sistema de gestión de la organización que se ocupa de la calidad <span class="pp">|</span></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Alcance** <span class="pp">|</span> Límites del sistema: qué parte de la organización y qué actividades cubre <span class="pp">|</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Información documentada** <span class="pp">|</span> Información que la organización debe controlar y mantener, y el medio que la contiene <span class="pp">|</span></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Eficacia / eficiencia** <span class="pp">|</span> Lograr lo planificado / relación entre el resultado y los recursos empleados <span class="pp">|</span></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **No conformidad** <span class="pp">|</span> Incumplimiento de un requisito <span class="pp">|</span></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>Fijaos en la conexión con el Tema 1: un **proceso** con entradas y salidas es un sistema, y el **alcance** es su frontera con el entorno.</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="fu"># Tareas</span></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>::: ejercicio</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>**La experiencia de la BUG**</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>: Moreno Pascual, L. (2016). <span class="co">[</span><span class="ot">El proceso de evaluación según el modelo EFQM: experiencia en la Biblioteca Universitaria de Granada</span><span class="co">](https://dialnet.unirioja.es/servlet/articulo?codigo=6530614)</span>. Boletín de la asociación andaluza de bibliotecarios, 31(112), 84-100.</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>**Objetivo.** Pasar de los principios abstractos de la ISO 9000 a evidencias concretas, distinguiendo qué corresponde a la organización y qué al punto de servicio.</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>**Instrucciones.**</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Localizad la documentación pública de calidad de la BUG (memorias EFQM, carta de servicios, política de calidad, resultados de encuestas) y la específica de la Biblioteca del Colegio Máximo (normas complementarias, información en la web, carteles, lo que observéis en persona).</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Para cada uno de los **7 principios**, buscad **una evidencia concreta**. Si no la encontráis, indicadlo: la ausencia también es un resultado.</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>Recogedlo en una tabla en el repositorio del caso práctico:</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>    | Principio | Evidencia | Fuente | Nivel (BUG / Colegio Máximo / ambos) | ¿Se aplica o solo se declara? |</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>    |---------------|---------------|---------------|---------------|---------------|</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>    La columna **Nivel** es obligatoria. Usad la pregunta de control: *si cerrara el Colegio Máximo, ¿esto seguiría existiendo?*</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>En vuestra página individual del wiki: ¿qué principio os ha costado más situar en un nivel y por qué?</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>**Entrega.** Commit al repositorio antes de que acabe la clase.</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>:::</span>
</code></pre></div><button title="Copiar al portapapeles" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/elrobin/aesde/edit/main/tema3/sesion1.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/elrobin/aesde/issues/new" class="toc-action"><i class="bi empty"></i>Informar sobre problema</a></li></ul></div></div></div></footer></body></html>